from langgraph.graph import StateGraph, START ,END
from langgraph.prebuilt import ToolNode,tools_condition
from Agents.RAGAgent import RAG_check_node
from Agents.TicketingAgent import create_ticket, lookup_ticket
from langchain_aws import ChatBedrockConverse
from langchain_core.messages import SystemMessage
import boto3
import os
from dotenv import load_dotenv
from utils.utility import  get_feedbackNode,AgentState,get_classificationNode
from langgraph.checkpoint.memory import MemorySaver
from pydantic import BaseModel,Field

from utils.Routers import rag_router, feedback_router

load_dotenv()

memory = MemorySaver()

SUPPORT_SYSTEM_PROMPT =  """
You are a proactive L1 IT Support Assistant. 
When RAG fails (confidence is low), follow these steps:
1. LOOK at the user's initial message and the classification results in the state.
2. AUTOMATICALLY generate a professional 'Title' and 'Description' based on their complaint.
3. Use the 'category' and 'priority' already provided in the state.
4. CALL the 'create_ticket' tool immediately. DO NOT ask the user for these details if they have already described their problem.
5. Only ask for missing information if the user's initial message was too vague (e.g., just saying 'help').
6. IMPORTANT: If the conversation history shows that a tool has already returned a 'ticket_id', DO NOT ask more questions. Simply say: 'I have successfully created a ticket for you. Your ticket ID is [ID]. A technician will contact you soon.' and then END the conversation.

If RAG succeeds (confidence is high), provide the relevant information to the user and ask if their issue is resolved. If they say 'yes', end the conversation. If they say 'no', proceed to create a ticket as described above.

"""

Novalite_model=ChatBedrockConverse(
    model="amazon.nova-lite-v1:0", 
    temperature=0, 
    region_name='us-east-1',
    aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
    aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
       
    )
FeedBackNode=get_feedbackNode(Novalite_model)
ClassificationNode=get_classificationNode(Novalite_model)


def ticketing_agent(state: AgentState):
    group = state.get("assignment_group", "IT_SUPPORT_L1")
    cat = state.get("category", "General")
    
   
    
    llm_with_tools = Novalite_model.bind_tools([create_ticket, lookup_ticket])
    full_messages=[SystemMessage(content=SUPPORT_SYSTEM_PROMPT)]+state["messages"]
    response=llm_with_tools.invoke(full_messages)
    return {"messages": [response]}


class FeedbackCheck(BaseModel):
    is_satisfied: bool = Field(description="True if the user is happy, False if they still have an issue.")
    
    
    

workFlow=StateGraph(AgentState)
workFlow.add_node("rag_check", RAG_check_node)
workFlow.add_node("feedback_check", FeedBackNode)
workFlow.add_node("ticketing_agent", ticketing_agent)
workFlow.add_node("tools", ToolNode([create_ticket, lookup_ticket]))
workFlow.add_node("classification_node", ClassificationNode)

workFlow.add_edge(START, "rag_check")
workFlow.add_conditional_edges(
    "rag_check", rag_router,{
        "feedback_check": "feedback_check",
        "classification_node": "classification_node"
    }
)

workFlow.add_conditional_edges(
    "feedback_check", feedback_router,{
        "end": END,
        "classification_node": "classification_node"
    }
)

workFlow.add_edge("classification_node", "ticketing_agent")

workFlow.add_conditional_edges("ticketing_agent", tools_condition)
workFlow.add_edge("tools", "ticketing_agent")

app = workFlow.compile(checkpointer=memory)

def main():
    # A unique ID for the conversation session
    config = {"configurable": {"thread_id": "test_session_1"}}
    
    print("--- Ticketing Support Bot (Type 'exit' to quit) ---")
    
    while True:
        user_input = input("User: ")
        if user_input.lower() in ["exit", "quit"]:
            break

        # Stream the output so you can see the 'thought process' of the graph
        for event in app.stream({"messages": [("user", user_input)]}, config):
            for value in event.values():
                # Print the last message generated by any node
                if "messages" in value:
                    last_msg = value["messages"][-1]
                    print("--- Debug: Current State Messages ---")
                    print(value["messages"])
                    print("--- Debug: Last Message ---")
                    print("last message:", last_msg)
                    print("--- End of Debug ---")
                    
                    
                    # Check if it's a list (from RAG) or a BaseMessage (from Nova)
                    msg_content = last_msg[1] if isinstance(last_msg, tuple) else last_msg.content
                    print(f"L1 support Assistant: {msg_content}")

if __name__ == "__main__":
    main()
